apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: ci
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: SONAR_HOST_URL
          valueFrom:
            secretKeyRef:
              name: sonar-secrets
              key: SONAR_HOST_URL
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: sonar-secrets
              key: SONAR_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ci
spec:
  selector:
    app: jenkins
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
