apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: ci
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:community
        env:
        - name: SONAR_JDBC_URL
          value: "jdbc:postgresql://postgres.ci.svc.cluster.local:5432/postgres"
        - name: SONAR_JDBC_USERNAME
          value: "postgres"
        - name: SONAR_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonar-secrets
              key: SONAR_DB_PASSWORD
        - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
          value: "true"
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: ci
spec:
  selector:
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000
  type: LoadBalancer